// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityManagementSystem.Models;

#nullable disable

namespace UtilityManagementSystem.Migrations
{
    [DbContext(typeof(UtilityDbContext))]
    partial class UtilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateOnly?>("BillDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<int>("ReadingId")
                        .HasColumnType("int")
                        .HasColumnName("ReadingID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Unpaid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BillId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("ReadingId");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComplaintID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<DateOnly?>("ComplaintDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int")
                        .HasColumnName("UtilityID");

                    b.HasKey("ComplaintId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HandledBy");

                    b.HasIndex("UtilityId");

                    b.ToTable("Complaint", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Active");

                    b.HasKey("CustomerId");

                    b.HasIndex(new[] { "ContactNumber" }, "UQ_Customer_ContactNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ_Customer_Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex(new[] { "Email" }, "UQ_Employee_Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ_Employee_Username")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Meter", b =>
                {
                    b.Property<int>("MeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MeterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeterId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int")
                        .HasColumnName("UtilityID");

                    b.HasKey("MeterId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UtilityId");

                    b.ToTable("Meter", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.MeterReading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReadingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingId"));

                    b.Property<decimal?>("Consumption")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([CurrentReading]-[PreviousReading])", true);

                    b.Property<decimal>("CurrentReading")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MeterId")
                        .HasColumnType("int")
                        .HasColumnName("MeterID");

                    b.Property<string>("Notes")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("PreviousReading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.HasKey("ReadingId");

                    b.HasIndex("MeterId");

                    b.HasIndex("RecordedBy");

                    b.ToTable("MeterReading", null, t =>
                        {
                            t.HasTrigger("TR_SetPreviousReading");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("BillID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex(new[] { "ReferenceNumber" }, "UQ_Payment_ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.ToTable("Payment", null, t =>
                        {
                            t.HasTrigger("TR_UpdateOutstandingBalance");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("ReportPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReportPeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Summary")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("ReportId");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TariffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal?>("FixedCharge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RatePerUnit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("SlabEnd")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SlabStart")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int")
                        .HasColumnName("UtilityID");

                    b.HasKey("TariffId");

                    b.HasIndex("UtilityId");

                    b.ToTable("Tariff", null, t =>
                        {
                            t.HasTrigger("TR_CloseTariff");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.UtilityTariffHistory", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ChangedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TariffId")
                        .HasColumnType("int")
                        .HasColumnName("TariffID");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int")
                        .HasColumnName("UtilityID");

                    b.HasKey("RecordId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TariffId");

                    b.HasIndex("UtilityId");

                    b.ToTable("UtilityTariffHistory", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.UtilityType", b =>
                {
                    b.Property<int>("UtilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UtilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UtilityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UtilityId");

                    b.HasIndex(new[] { "UtilityName" }, "UQ_UtilityType_UtilityName")
                        .IsUnique();

                    b.ToTable("UtilityType", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.VwComplaintsSummary", b =>
                {
                    b.Property<DateOnly?>("ComplaintDate")
                        .HasColumnType("date");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int")
                        .HasColumnName("ComplaintID");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(101)
                        .IsUnicode(false)
                        .HasColumnType("varchar(101)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int")
                        .HasColumnName("UtilityID");

                    b.ToTable((string)null);

                    b.ToView("vw_ComplaintsSummary", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.VwMonthlyRevenue", b =>
                {
                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_MonthlyRevenue", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.VwTopConsumer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(101)
                        .IsUnicode(false)
                        .HasColumnType("varchar(101)");

                    b.Property<decimal?>("TotalConsumption")
                        .HasColumnType("decimal(38, 2)");

                    b.ToTable((string)null);

                    b.ToView("vw_TopConsumers", (string)null);
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.VwUnpaidBill", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("BillID");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.ToTable((string)null);

                    b.ToView("vw_UnpaidBills", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Bill", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.Customer", "Customer")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Bill_Customer");

                    b.HasOne("UtilityManagementSystem.Models.Employee", "GeneratedByNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("GeneratedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Bill_Employee");

                    b.HasOne("UtilityManagementSystem.Models.MeterReading", "Reading")
                        .WithMany("Bills")
                        .HasForeignKey("ReadingId")
                        .IsRequired()
                        .HasConstraintName("FK_Bill_MeterReading");

                    b.Navigation("Customer");

                    b.Navigation("GeneratedByNavigation");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Complaint", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.Customer", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Complaint_Customer");

                    b.HasOne("UtilityManagementSystem.Models.Employee", "HandledByNavigation")
                        .WithMany("Complaints")
                        .HasForeignKey("HandledBy")
                        .HasConstraintName("FK_Complaint_Employee");

                    b.HasOne("UtilityManagementSystem.Models.UtilityType", "Utility")
                        .WithMany("Complaints")
                        .HasForeignKey("UtilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Complaint_UtilityType");

                    b.Navigation("Customer");

                    b.Navigation("HandledByNavigation");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Meter", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.Customer", "Customer")
                        .WithMany("Meters")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Meter_Customer");

                    b.HasOne("UtilityManagementSystem.Models.UtilityType", "Utility")
                        .WithMany("Meters")
                        .HasForeignKey("UtilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Meter_UtilityType");

                    b.Navigation("Customer");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.MeterReading", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.Meter", "Meter")
                        .WithMany("MeterReadings")
                        .HasForeignKey("MeterId")
                        .IsRequired()
                        .HasConstraintName("FK_MeterReading_Meter");

                    b.HasOne("UtilityManagementSystem.Models.Employee", "RecordedByNavigation")
                        .WithMany("MeterReadings")
                        .HasForeignKey("RecordedBy")
                        .IsRequired()
                        .HasConstraintName("FK_MeterReading_Employee");

                    b.Navigation("Meter");

                    b.Navigation("RecordedByNavigation");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Payment", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Bill");

                    b.HasOne("UtilityManagementSystem.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Customer");

                    b.HasOne("UtilityManagementSystem.Models.Employee", "ProcessedByNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("ProcessedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Employee");

                    b.Navigation("Bill");

                    b.Navigation("Customer");

                    b.Navigation("ProcessedByNavigation");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Report", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.Employee", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Report_Employee");

                    b.Navigation("GeneratedByNavigation");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Tariff", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.UtilityType", "Utility")
                        .WithMany("Tariffs")
                        .HasForeignKey("UtilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Tariff_UtilityType");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.UtilityTariffHistory", b =>
                {
                    b.HasOne("UtilityManagementSystem.Models.Employee", "ChangedByNavigation")
                        .WithMany("UtilityTariffHistories")
                        .HasForeignKey("ChangedBy")
                        .IsRequired()
                        .HasConstraintName("FK_UTH_Employee");

                    b.HasOne("UtilityManagementSystem.Models.Tariff", "Tariff")
                        .WithMany("UtilityTariffHistories")
                        .HasForeignKey("TariffId")
                        .IsRequired()
                        .HasConstraintName("FK_UTH_Tariff");

                    b.HasOne("UtilityManagementSystem.Models.UtilityType", "Utility")
                        .WithMany("UtilityTariffHistories")
                        .HasForeignKey("UtilityId")
                        .IsRequired()
                        .HasConstraintName("FK_UTH_UtilityType");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Tariff");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Customer", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Complaints");

                    b.Navigation("Meters");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Complaints");

                    b.Navigation("MeterReadings");

                    b.Navigation("Payments");

                    b.Navigation("Reports");

                    b.Navigation("UtilityTariffHistories");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Meter", b =>
                {
                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.MeterReading", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.Tariff", b =>
                {
                    b.Navigation("UtilityTariffHistories");
                });

            modelBuilder.Entity("UtilityManagementSystem.Models.UtilityType", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Meters");

                    b.Navigation("Tariffs");

                    b.Navigation("UtilityTariffHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
